In [11]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [12]:
env = gym.make("FrozenLake-v0")

In [13]:
#Initializing the parameters on enviroment
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Setting up the environment parameters

num_episodes = 10000               #The no. epsiode we want our agent to play during training.
max_steps_per_episode = 100       #Max no. of steps agent allowed to take during single episode.

learning_rate = 0.1
discount_rate = 0.99


#Parameters related to exploitation greedy-strategy.

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.0001
exploration_decay_rate = 0.001


In [15]:
rewards_all_episodes = []
#Q-learning Algorithm
for episode in range(num_episodes):
 
    """
    For each episode we are going
    back to starting state.
    """
    
    state = env.reset()
    done = False                     #Just to keep track that whether our episode is finished or not.
    rewards_current_episode = 0      #Reset reward
    
    
    for step in range(max_steps_per_episode):
         
        """
        Nested loop which run for each timestamp
        within an episode.
        """
        
        #Exploration-rate trade off:
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state , reward , done, info = env.step(action)
        
        # Update Q-table for (s,a)
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
    
    
    #Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand reward
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)    

KeyboardInterrupt: 

In [ ]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        # Take new action
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state    

env.close()

  (Up)
SFFF
FHFH
FFFH
HFFG
